test = input ("Digite alguma coisa:  ")
print ("O tipo primitivo desse valor é", type(test))
if test.isspace(): print ("O seu texto só possui espaços ")
if test.isnumeric(): print ("Você digitou um numero")
if test.isalpha(): print ("Você digitou uma letra ou frase")
if test.isupper(): print ("O seu texto está em MAISCULO") 
if test.islower(): print ("O seu texto está em MINUSCULO")
if test.isalnum(): print ("Você digitou uma frase que possui numeros e ou letras")
else : print ("Você não digitou nada ou  o texto não contém numeros ou letras")